# -*- coding: utf-8 -*-
"""aslinterpreter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7vAJE0Qzx7nL4g8AYR8PPK84lVyuk8S
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import os

train_dir = '/kaggle/input/datasets/grassknoted/asl-alphabet/asl_alphabet_train/asl_alphabet_train'

IMAGE_SIZE = 224
BATCH_SIZE = 32

train_data_generation = ImageDataGenerator(
    rescale = 1./255,
    validation_split = 0.2,
    rotation_range = 15,
    zoom_range = 0.2,
    width_shift_range = 0.1,
    height_shift_range = 0.1

)

train_generator = train_data_generation.flow_from_directory(
    train_dir,
    target_size = (IMAGE_SIZE, IMAGE_SIZE),
    batch_size = BATCH_SIZE,
    class_mode = 'categorical',
    subset = 'training'

)

val_generator = train_data_generation.flow_from_directory(
    train_dir,
    target_size = (IMAGE_SIZE, IMAGE_SIZE),
    batch_size = BATCH_SIZE,
    class_mode = 'categorical',
    subset = 'validation'
)

base_model = MobileNetV2(
    weights = 'imagenet',
    include_top = False,
    input_shape = (224,224,3)

)

base_model.trainable = False

x = base_model.output

x = GlobalAveragePooling2D()(x)

x = Dropout(0.3)(x)

x = Dense(128, activation='relu')(x)

predictions = Dense(train_generator.num_classes, activation='softmax')(x)

model = Model(inputs = base_model.input, outputs = predictions)

model.compile(optimizer=Adam(learning_rate=0.001),loss='categorical_crossentropy',metrics=['accuracy'])

model.summary()

history = model.fit(
    train_generator,
    validation_data  = val_generator,
    epochs = 5
)

model.save('asl_model.keras')