# -*- coding: utf-8 -*-
"""prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doU8epC-u_eNGDCJ32VllrVV-jBr7lnI
"""

!pip install mediapipe opencv-python

from tensorflow.keras.models import load_model
model = load_model('/content/asl_model.keras')
print('Model Loaded Successfully')

with open('/content/labels.txt','r') as f:
  labels = [line.strip() for line in f.readlines()]

print(labels)

import cv2
import numpy as np
import matplotlib.pyplot as plt

image_path = '/content/A_test.jpg'

img = cv2.imread(image_path)

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

resized = cv2.resize(img_rgb, (224, 224))

normalised = resized/255.0

input_image = np.expand_dims(normalised, axis =0)

prediction = model.predict(input_image)

predicted = np.argmax(prediction)

label = labels[predicted]

confidence = np.max(prediction)

plt.imshow(img_rgb)
plt.title(f'Prediction : {label} | Confidence: {confidence:.2f}')
plt.axis('off')
plt.show()